version: '3'

services:

  fata:
    build:
      context: .
      dockerfile: docker/Dockerfile

  php-fpm:
    build: docker
    container_name: 'php'
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: roadsurfer
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: superadmin
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  openapi-generator:
    image: openapitools/openapi-generator-cli:latest
    volumes:
      - ./:/local
    command: [ "generate", "-i", "/local/apidoc.yaml", "-g", "php-dt", "-o", "/local/api-client" ]

volumes:
  database_data:
