create_activity:
  path: /api/v1/activity
  controller: App\Controller\ActivityController::createActivity
  methods: POST

create_user:
  path: /api/v1/user
  controller: App\Controller\UserController::createUser
  methods: POST

get_activities:
  path: /api/v1/activities
  controller: App\Controller\ActivityController::getActivities
  methods: GET

get_distance_by_type:
  path: /api/v1/activities/distance
  controller: App\Controller\ActivityController::getDistanceByType
  methods: GET

get_elapsed_time_by_type:
  path: /api/v1/activities/elapsed_time
  controller: App\Controller\ActivityController::getElapsedTimeByType
  methods: GET

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }